name: Tagged Release on Release-Now Commit Message

on:
  push:
    paths:
      - 'vencord/Vertical-Spacious-Refresh.css'

jobs:
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.event.head_commit.message, 'Release-Now')

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Generate version based on date and time
      id: get_version
      run: |
        VERSION=$(date +'%Y-%m-%d-%H%M%S')
        echo "Generated version: $VERSION"
        echo "version=$VERSION" >> $GITHUB_ENV  # Store version in environment variable

    - name: Log generated version
      run: |
        echo "Generated version: ${{ env.version }}"  # Use environment variable to access the version

    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "v${{ env.version }}"
        name: "Release ${{ env.version }}"
        files: vencord/Vertical-Spacious-Refresh.css
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
